import { createFileRoute, Link } from "@tanstack/react-router";
import { Award, Crown, Gem, Star } from "lucide-react";
import PlatformHeader from "@/components/PlatformHeader";
import { Button } from "@/components/ui/button";
import { SPONSORS, money, tierFor } from "@/lib/platform";
export const Route = createFileRoute("/sponsors-hall")({ head: () => ({ meta: [
  { title: "Sponsors Hall of Fame — Algerio" }, { name: "description", content: "Meet the organizations supporting Algeria's open website directory." },
  { property: "og:title", content: "Sponsors Hall of Fame — Algerio" }, { property: "og:description", content: "The organizations supporting The Algerian Index by Algerio." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
]}), component: SponsorsHall });
const TierIcon = ({ spent }: { spent: number }) => { const t = tierFor(spent).name; return t === "Elite Sponsor" ? <Crown className="h-4 w-4" /> : t === "Premium Sponsor" ? <Gem className="h-4 w-4" /> : <Star className="h-4 w-4" />; };
function SponsorsHall() { const ranked = [...SPONSORS].sort((a,b) => b.spent-a.spent); const podium = [ranked[1], ranked[0], ranked[2]].filter(Boolean); return <><PlatformHeader /><main className="mx-auto max-w-6xl px-4 py-14"><div className="mx-auto max-w-2xl text-center"><Award className="mx-auto h-10 w-10 text-primary" /><h1 className="mt-4 text-4xl font-bold">Sponsors Hall of Fame</h1><p className="mt-3 text-muted-foreground">The organizations helping Algerio map and celebrate Algeria’s digital ecosystem.</p><Button asChild className="mt-6 rounded-full bg-foreground text-background"><Link to="/sponsors">Become a sponsor</Link></Button></div><div className="mt-14 grid items-end gap-4 sm:grid-cols-3">{podium.map((s,i) => s && <article key={s.name} className={`rounded-2xl border border-border p-6 text-center ${i === 1 ? "sm:min-h-72" : "sm:min-h-60"}`}><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-muted text-3xl">{s.logo}</div><p className="mt-4 text-xs font-semibold uppercase text-muted-foreground">#{i === 1 ? 1 : i === 0 ? 2 : 3}</p><h2 className="mt-1 text-xl font-bold">{s.name}</h2><p className="text-sm text-muted-foreground">{s.industry}</p><span className="mt-4 inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-medium"><TierIcon spent={s.spent} />{tierFor(s.spent).name}</span><p className="mt-3 font-semibold">{money(s.spent)}</p></article>)}</div><div className="mt-10 overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/60"><tr><th className="p-4">Rank</th><th className="p-4">Sponsor</th><th className="p-4">Industry</th><th className="p-4">Since</th><th className="p-4">Badge</th><th className="p-4 text-right">Support</th></tr></thead><tbody>{ranked.map((s,i) => <tr key={s.name} className="border-t border-border"><td className="p-4 font-semibold">#{i+1}</td><td className="p-4 font-medium">{s.logo} {s.name}</td><td className="p-4 text-muted-foreground">{s.industry}</td><td className="p-4 text-muted-foreground">{s.since}</td><td className="p-4"><span className="inline-flex items-center gap-2 rounded-full bg-muted px-3 py-1 text-xs"><TierIcon spent={s.spent}/>{tierFor(s.spent).name}</span></td><td className="p-4 text-right font-semibold">{money(s.spent)}</td></tr>)}</tbody></table></div></main></>; }
