/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SponsorsHallRouteImport } from './routes/sponsors-hall'
import { Route as SubmitRouteImport } from './routes/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsHallRoute = SponsorsHallRouteImport.update({
  id: '/sponsors-hall',
  path: '/sponsors-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/sponsors': typeof SponsorsRoute
  '/sponsors-hall': typeof SponsorsHallRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/sponsors': typeof SponsorsRoute
  '/sponsors-hall': typeof SponsorsHallRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/sponsors': typeof SponsorsRoute
  '/sponsors-hall': typeof SponsorsHallRoute
  '/submit': typeof SubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/owner-dashboard'
    | '/sponsors'
    | '/sponsors-hall'
    | '/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/owner-dashboard'
    | '/sponsors'
    | '/sponsors-hall'
    | '/submit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/owner-dashboard'
    | '/sponsors'
    | '/sponsors-hall'
    | '/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  SponsorsRoute: typeof SponsorsRoute
  SponsorsHallRoute: typeof SponsorsHallRoute
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors-hall': {
      id: '/sponsors-hall'
      path: '/sponsors-hall'
      fullPath: '/sponsors-hall'
      preLoaderRoute: typeof SponsorsHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  SponsorsRoute: SponsorsRoute,
  SponsorsHallRoute: SponsorsHallRoute,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
